# Generated by Django 3.2.9 on 2021-12-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listings_highestbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='highestbidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestbidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
