# Generated by Django 3.2.9 on 2021-12-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listings_highestbidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_wishlist', related_query_name='wish', to='auctions.auction_listings'),
        ),
    ]
